export const RESPONSE_PENDING = 'RESPONSE_PENDING';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
